language: ruby
dist: trusty
cache: bundler
sudo: required
env:
  - ES=1 TEST_GROUP="./script/check_syntax"
  - ES=2 TEST_GROUP="cucumber --tag ~@old-search -r features features/other_b            -f Ao3Cucumber::Formatter --color"
rvm:
  - "`cat .ruby_version| sed -e 's/ruby //'`"
services:
  - elasticsearch
  - redis-server
  - memcached
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec $TEST_GROUP
before_script:
  - bash script/travis_configure.sh
  - bash script/travis_elasticsearch_upgrade.sh
  - bash script/travis_multiple_redis.sh
notifications:
  email:
    recipients:
      - otw-coders-extra@transformativeworks.org
    on_success: change
    on_failure: always
  irc:
   channels:
     - "irc.freenode.org#otw-dev"
   on_success: change
   on_failure: change
