language: ruby
dist: trusty
cache: bundler
sudo: required
env:
  - TEST_GROUP="rspec spec/miscellaneous"
  - TEST_GROUP="cucumber -r features features/to_run             -f Ao3Cucumber::Formatter --color"
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
rvm:
  - "`cat .ruby_version| sed -e 's/ruby //'`"
services:
  - redis-server
  - memcached
script:
  - RAILS_ENV=test bundle exec rake db:schema:load --trace
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec $TEST_GROUP
before_script:
  - bash script/travis_configure.sh
  - bash script/travis_elasticsearch_upgrade.sh
  - bash script/travis_multiple_redis.sh
  - bash script/travis_mysql.sh
after_failure:
  - tail -v -n +1 $TRAVIS_BUILD_DIR/tmp/capybara/*.html
notifications:
  email:
    recipients:
      - otw-coders-extra@transformativeworks.org
    on_success: change
    on_failure: always
  irc:
   channels:
     - "irc.freenode.org#otw-dev"
   on_success: change
   on_failure: change
